version: '3.4'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadm
      MONGO_INITDB_ROOT_PASSWORD: mongopass

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadm
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopass

  warden:
    build: .
    restart: on-failure
    depends_on:
      - mongo
    environment:
      token: "${token}"
      prefix: "${prefix}"
